<template>
  <section class="knowledge">
    <div class="hero"><div><small>PERSONAL MEMO</small><h2>备忘录</h2><p>把灵感、资料和重要链接收进一个轻巧的空间。</p></div><button class="primary" @click="newCard">＋ 新建备忘</button></div>
    <form class="search" @submit.prevent="search"><input v-model="keyword" placeholder="输入关键词，结果会自动出现" /><button>搜索</button></form>
    <p v-if="searched" class="stats">精确匹配 {{ exact }} 条 · 语义匹配 {{ semantic }} 条</p><p v-if="error" class="error">{{ error }}</p>
    <div class="layout"><div class="cards"><article v-for="card in cards" :key="card.id" class="card"><div class="head"><div><span v-if="card.match_type" class="match">{{ card.match_type === 'exact' ? '精确匹配' : `语义匹配 ${Math.round(card.score * 100)}%` }}</span><h3>{{ card.title }}</h3></div><div><button @click="edit(card)">编辑</button><button class="danger" @click="remove(card)">删除</button></div></div><div class="tags"><span v-for="tag in card.tags" :key="tag">#{{ tag }}</span></div><p v-if="card.content" class="content"><a v-if="isLinkCard(card)" :href="linkUrl(card.content)" target="_blank" rel="noopener noreferrer">{{ card.content }}</a><template v-else>{{ card.content }}</template></p><img v-if="card.image_url" class="knowledge-image" :src="card.image_url" :alt="card.title" /><p v-if="card.related.length" class="meta"><b>关联：</b>{{ card.related.join(' · ') }}</p><p v-if="card.notes" class="meta"><b>我的笔记：</b>{{ card.notes }}</p></article><p v-if="!cards.length" class="empty">暂无知识卡片</p></div>
      <form v-if="editing" class="editor" @submit.prevent="save"><div class="editor-top"><h3>{{ form.id ? '编辑知识' : '新建知识' }}</h3><button type="button" class="close-editor" @click="editing=false">×</button></div><p class="quick-hint">文字和图片任选其一，也可以同时添加。</p><label>标题<input v-model="form.title" placeholder="例如：FedAvg" required /></label><label>标签（逗号分隔）<input v-model="form.tags" placeholder="联邦学习, 聚合算法" /></label><label>内容<textarea v-model="form.content" rows="8" placeholder="文字内容（可选）" /></label><div class="image-drop" @dragover.prevent @drop="onDrop" @click="imagePicker.click()"><input ref="imagePicker" type="file" accept="image/png,image/jpeg,image/gif,image/webp" hidden @change="chooseImage($event.target.files[0])" /><strong>添加图片</strong><span>拖入图片，或点击从本地选择</span><small>支持 PNG、JPG、GIF、WebP，最大 10MB</small><em v-if="imageName">已选择：{{ imageName }}</em></div><p v-if="formError" class="error">{{ formError }}</p><div class="editor-actions"><button type="button" class="ghost-btn" @click="editing=false">取消</button><button type="submit" class="primary">保存到数据库</button></div></form>
    </div>
  </section>
</template>

<script setup>
import './knowledge-compact.css'
import { onMounted, reactive, ref, watch } from 'vue'
import { createKnowledge, deleteKnowledge, listKnowledge, searchKnowledge, updateKnowledge, uploadKnowledgeImage } from '../api'
const cards=ref([]),keyword=ref(''),searched=ref(false),editing=ref(false),error=ref(''),formError=ref(''),exact=ref(0),semantic=ref(0),imageName=ref(''),imagePicker=ref(null)
const form=reactive({id:null,title:'',tags:'',content:'',related:'',notes:'',image:null});let timer
const msg=e=>e?.response?.data?.detail||'操作失败';const split=v=>v.split(/[,，\n]+/).map(x=>x.trim().replace(/^#/,'')).filter(Boolean)
async function load(){try{cards.value=await listKnowledge()}catch(e){error.value=msg(e)}}
async function search(){if(!keyword.value.trim()){searched.value=false;return load()}try{const r=await searchKnowledge(keyword.value);cards.value=r.items;exact.value=r.exact_count;semantic.value=r.semantic_count;searched.value=true}catch(e){error.value=msg(e)}}
watch(keyword,()=>{clearTimeout(timer);timer=setTimeout(search,260)})
function isLinkCard(card){return card.tags?.some(t=>['网址','链接','url','link'].includes(String(t).toLowerCase()))}
function linkUrl(value){const v=value.trim();return /^https?:\/\//i.test(v)?v:`https://${v}`}
function newCard(){Object.assign(form,{id:null,title:'',tags:'',content:'',related:'',notes:'',image:null});imageName.value='';formError.value='';editing.value=true}
function edit(c){Object.assign(form,{id:c.id,title:c.title,tags:c.tags.join(', '),content:c.content,related:c.related.join(', '),notes:c.notes||'',image:null});imageName.value='';editing.value=true}
function chooseImage(file){if(!file)return;if(!file.type.startsWith('image/')){formError.value='请选择图片文件';return}form.image=file;imageName.value=file.name}
function onDrop(e){e.preventDefault();chooseImage(e.dataTransfer.files?.[0])}
async function save(){if(!form.title.trim()||(!form.content.trim()&&!form.image)){formError.value='请输入文字内容或添加一张图片';return}const body={title:form.title,tags:split(form.tags),content:form.content,related:split(form.related),notes:form.notes||null};try{const saved=form.id?await updateKnowledge(form.id,body):await createKnowledge(body);if(form.image)await uploadKnowledgeImage(saved.id,form.image);editing.value=false;searched.value?await search():await load()}catch(e){formError.value=msg(e)}}
async function remove(c){if(!confirm(`确定删除“${c.title}”吗？`))return;try{await deleteKnowledge(c.id);cards.value=cards.value.filter(x=>x.id!==c.id)}catch(e){error.value=msg(e)}}
onMounted(load)
</script>
<style scoped>.knowledge{width:100%}.hero{display:flex;justify-content:space-between;padding:26px 30px;background:#eef2ff;border-radius:16px;margin-bottom:18px}.hero small{color:#6554d9}.hero h2{margin:5px 0}.hero p{color:#687086}.primary,.search button{background:#6554d9;color:#fff;border:0;border-radius:8px;padding:10px 16px;cursor:pointer}.search{display:flex;background:#fff;padding:8px;border:1px solid #e2e5ec;border-radius:10px}.search input{flex:1;border:0;padding:10px;outline:0}.stats{color:#6554d9}.layout{display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:16px;margin-top:14px}.cards{display:grid;gap:14px}.card,.editor,.empty{background:#fff;border:1px solid #e6e8ef;border-radius:12px;padding:20px}.head{display:flex;justify-content:space-between}.head button{border:0;background:none;cursor:pointer}.danger{color:#c33}.match,.tags span{font-size:12px;color:#5e52b5;background:#f0effb;padding:4px 8px;border-radius:6px}.card h3{margin:8px 0}.tags{display:flex;gap:7px;margin:12px 0}.content{white-space:pre-wrap;line-height:1.7}.content a{color:#5e52b5;text-decoration:underline;text-underline-offset:4px;cursor:pointer}.content a:hover{color:#3d30b3}.knowledge-image{display:block;max-width:100%;max-height:480px;object-fit:contain;border-radius:12px;margin-top:14px}.meta{border-top:1px solid #eee;padding-top:9px;color:#687086}.editor{height:max-content}.editor label{display:block;margin:12px 0;font-size:13px}.editor input,.editor textarea{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid #ddd;border-radius:7px;font:inherit}.image-drop{display:flex;flex-direction:column;align-items:center;gap:6px;padding:24px 14px;margin:14px 0;border:1.5px dashed #b9b5e8;border-radius:14px;background:#fafaff;color:#6554d9;cursor:pointer;text-align:center}.image-drop span,.image-drop small{color:#85859a;font-size:12px}.image-drop em{font-size:12px;color:#25855a;font-style:normal}.error{color:#c33}@media(max-width:800px){.layout{grid-template-columns:1fr}}</style>
